#!/bin/bash

# set -e

# SCRIPTDIR=$(dirname "$0")
# source $SCRIPTDIR/env.sh

# # =====================================================

# export ANDROID_ARCH="NEED TO CUSTOMIZED"							# Qt >= 5.14 supports android multi-ABI builds have a look in pro-files
# export ANDROID_SDK_ROOT="NEED TO CUSTOMIZED" 					 	# Your full basic path to your Android SDK tools do not use ~/ 
# export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT=/ndk/22.1.7171670	  		# path to Google NDK use this NDK
# export QT_MKSPEC=android-clang  								    # android-clang or android-g++

# #
# export JDK_PATH=/usr/lib/jvm/java-17-openjdk-amd64					# you can use openjdk 11, too
# export JAVA_HOME=$JDK_PATH
# export PATH=$JAVA_HOME/bin:$PATH

# # =====================================================

# QT_PATH_RUNTIME=$QT_BASE_PATH/$QT_VERSION/$ANDROID_ARCH
# BUILD_DIR=$ANDROID_ARCH-$SHADOW_BUILD_DIR
# BUILD_TARGET=android-build

set -e

SCRIPTDIR=$(dirname "$0")
source $SCRIPTDIR/env.sh

# =====================================================

export ANDROID_ARCH="android"							# Qt >= 5.14 supports android multi-ABI builds have a look in pro-files
export ANDROID_SDK_ROOT="C:/Users/Training/AppData/Local/Android/Sdk" 					 	# Your full basic path to your Android SDK tools do not use ~/ 
export ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/22.1.7171670	  		# path to Google NDK use this NDK
export QT_MKSPEC=android-clang  								    # android-clang or android-g++

#
export JDK_PATH="C:/Users/Training/jdk11"
export JAVA_HOME=$(cygpath -u "$JDK_PATH")
export PATH="$JAVA_HOME/bin:$PATH"

echo "Checking Java configuration..."
java -version
which java
echo "JAVA_HOME is set to: $JAVA_HOME"

# =====================================================

QT_PATH_RUNTIME=$QT_BASE_PATH/$QT_VERSION/$ANDROID_ARCH
BUILD_DIR=$ANDROID_ARCH-$SHADOW_BUILD_DIR
BUILD_TARGET=android-build

echo 
echo ========== enter shadowbuild dir 
echo 
mkdir -p $BUILD_DIR
cd $BUILD_DIR

echo 
echo ========== prepare build 
echo 
$QT_PATH_RUNTIME/bin/qmake -r -spec $QT_MKSPEC "$GARLIC_DIR/src/complete_c2qml.pro" CONFIG+=$CONFIG_DEBUG_RELEASE CONFIG+=qml_$CONFIG_DEBUG_RELEASE CONFIG+=android ANDROID_ABIS="armeabi-v7a arm64-v8a"
find . -name "Makefile*" -exec touch {} +

echo 
echo ========== build 
echo 
"$ANDROID_NDK_ROOT/prebuilt/windows-x86_64/bin/make" -j $DEV_JOBS QMAKE="echo skipping qmake" 2>&1 | tee build_log.txt
BUILD_EXIT=${PIPESTATUS[0]}
if [ $BUILD_EXIT -ne 0 ]; then
    echo "ERROR: make failed with exit code $BUILD_EXIT. Check build_log.txt for details."
    exit $BUILD_EXIT
fi

echo 
echo ========== run ranlib on static libraries 
echo 
if [ -f "libandroid/libgarlic_armeabi-v7a.a" ]; then
    "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib" libandroid/libgarlic_armeabi-v7a.a
    echo "ranlib: armeabi-v7a done"
else
    echo "WARNING: libgarlic_armeabi-v7a.a not found - skipping ranlib for this ABI"
fi
if [ -f "libandroid/libgarlic_arm64-v8a.a" ]; then
    "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android-ranlib" libandroid/libgarlic_arm64-v8a.a
    echo "ranlib: arm64-v8a done"
else
    echo "WARNING: libgarlic_arm64-v8a.a not found - skipping ranlib for this ABI"
fi

echo 
echo ========== pack apk with gradle 
echo 
rm -rf $BUILD_TARGET
find . -name "Makefile*" -exec touch {} +
"$ANDROID_NDK_ROOT/prebuilt/windows-x86_64/bin/make" QMAKE="echo skipping qmake" INSTALL_ROOT=$BUILD_TARGET install

# Verify deployment settings exist
if [ ! -f "./player-c2qml/android-la-player-deployment-settings.json" ]; then
    echo "ERROR: deployment settings file not found!"
    exit 1
fi

$QT_PATH_RUNTIME/bin/androiddeployqt \
	--input ./player-c2qml/android-la-player-deployment-settings.json \
	--output ./player-c2qml/$BUILD_TARGET \
	--deployment bundled \
	--android-platform $ANDROID_API_VERSION \
	--jdk "$JDK_PATH"  \
	--no-gradle \
	--$CONFIG_DEBUG_RELEASE \
	--verbose

# Run Gradle manually
if [ ! -f "./player-c2qml/$BUILD_TARGET/gradlew" ]; then
    echo "ERROR: gradlew not generated by androiddeployqt!"
    exit 1
fi

cd ./player-c2qml/$BUILD_TARGET
./gradlew -Dhttps.protocols=TLSv1.2 assemble${CONFIG_DEBUG_RELEASE^} --build-cache --parallel --daemon
cd ../..

APK_PATH="./player-c2qml/$BUILD_TARGET/build/outputs/apk/$CONFIG_DEBUG_RELEASE"
if [ -d "$APK_PATH" ]; then
    mv $APK_PATH/*.apk la-player-$ANDROID_ARCH-$DEPLOY_SUFFIX-$CONFIG_DEBUG_RELEASE.apk
    echo "Build SUCCESSFUL: APK moved to root directory."
else
    echo "ERROR: APK directory not found after gradle build!"
    exit 1
fi
